# Generated by Django 4.0.1 on 2022-05-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='quantity',
            new_name='discount',
        ),
    ]
